# Generated by Django 3.2.3 on 2021-05-29 13:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('age', models.IntegerField()),
                ('location', models.CharField(max_length=200)),
                ('profession', models.CharField(max_length=200)),
                ('institution', models.CharField(max_length=200)),
                ('social_link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Initiative',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('site', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('site', models.URLField(blank=True, null=True, unique=True)),
                ('location', models.CharField(max_length=200)),
                ('is_club', models.BooleanField()),
                ('institution', models.CharField(blank=True, max_length=100, null=True)),
                ('popularity', models.CharField(choices=[('High', 'High'), ('Mid', 'Mid'), ('Low', 'Low')], default='Mid', max_length=4)),
                ('is_active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date', models.DateField(blank=True, null=True)),
                ('link', models.URLField()),
                ('can_display', models.BooleanField()),
                ('followed_initiative', models.ManyToManyField(blank=True, related_name='resource_initiative', to='core.Initiative')),
                ('parent_org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='post_org', to='core.organization')),
                ('related_tag', models.ManyToManyField(blank=True, related_name='resource_tag', to='core.Tag')),
            ],
        ),
        migrations.AddField(
            model_name='organization',
            name='related_tag',
            field=models.ManyToManyField(blank=True, related_name='org_tag', to='core.Tag'),
        ),
        migrations.AddField(
            model_name='initiative',
            name='parent_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='initiative_org', to='core.organization'),
        ),
        migrations.AddField(
            model_name='initiative',
            name='related_tag',
            field=models.ManyToManyField(blank=True, related_name='initiative_tag', to='core.Tag'),
        ),
    ]
