# Generated by Django 3.2.3 on 2021-05-30 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_useradditionalinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer',
            name='initiative_part',
            field=models.ManyToManyField(blank=True, related_name='consumer_initiative', to='core.Initiative'),
        ),
        migrations.AddField(
            model_name='consumer',
            name='send_newsletter',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
