# Generated by Django 3.2.3 on 2021-05-31 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210530_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useradditionalinfo',
            name='profile_pic',
        ),
    ]
